services:
  excalibur:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/erwanb44300/excalibur:latest
    working_dir: /opt/excalibur
    stdin_open: true
    tty: true
    volumes:
      - ./artifacts:/opt/excalibur/artifacts
      - ./Cheetsheet.md:/opt/excalibur/Cheetsheet.md:ro
    command: ["profiles"]
